=== udit-pandya/xml-and-js/week-3/assignments/activity-1.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (productName, manufacturer, description?, prices, productItems)>
<!ELEMENT productName (#PCDATA)>
<!ATTLIST productName company CDATA #REQUIRED>
<!ELEMENT manufacturer (#PCDATA)>
<!ATTLIST manufacturer name CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description length CDATA #REQUIRED>
<!ELEMENT prices (price)+>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #IMPLIED> 
<!ELEMENT productItems (#PCDATA)>
<!ATTLIST productItems items CDATA #IMPLIED>

=== udit-pandya/xml-and-js/week-3/assignments/activity-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE products SYSTEM "./activity-1.dtd">
<!-- <!DOCTYPE products
[
    <!ELEMENT products (product+)>
    <!ELEMENT product (productName, manufacturer, description?, prices, productItems)>
    <!ELEMENT productName (#PCDATA)>
    <!ATTLIST productName company CDATA #REQUIRED>
    <!ELEMENT manufacturer (#PCDATA)>
    <!ATTLIST manufacturer name CDATA #REQUIRED>
    <!ELEMENT description (#PCDATA)>
    <!ATTLIST description length CDATA #REQUIRED>
    <!ELEMENT prices (price)+>
    <!ELEMENT price (#PCDATA)>
    <!ATTLIST price currency CDATA #IMPLIED> 
    <!ELEMENT productItems (#PCDATA)>
    <!ATTLIST productItems items CDATA #IMPLIED>
]> -->
<products>
  <product>
    <productName company="A">Dog Shirt Gift Basket</productName>
    <manufacturer name="A">SJB Pet Boutique&#153;</manufacturer>
    <description length="15">Something for every day of the week</description>
    <prices>
      <price>US$35.99</price>
      <price>CAD$44.99</price>
      <price>&#8364;26.79</price>
    </prices>
    <productItems >1200, 1201, 1202, 1203, 1204, 1205, 1206</productItems>
  </product>
  <product>
    <productName company="B">Car Curiosity Basket</productName>
    <manufacturer name="B">SJB Pet Boutique&#153;</manufacturer>
    <description length="15">Playtime morning, noon, and night</description>
    <prices>
      <price>US$15.99</price>
      <price>CAD$18.82</price>
      <price>&#8364;11.90</price>
    </prices>
    <productItems>4430, 6500, 4434</productItems>
  </product>
  <product>
    <productName company="C">Piggy Snuggle Basket</productName>
    <manufacturer name="C">ACME&#153;</manufacturer>
    <prices>
      <price>US$17.50</price>
      <price>CAD$21.96</price>
      <price>&#8364;13.03</price>  
    </prices>
    <productItems>3230, 3232</productItems>
  </product>
  <product>
    <productName company="D">Dog Snuggle Basket</productName>
    <manufacturer name="D">ACME&#153;</manufacturer>
    <prices>
      <price currency="USD">US$14.25</price>
      <price currency="CAD">CAD$17.88</price>
      <price currency="EU">&#8364;10.61</price>
    </prices>
    <productItems items="any">3230, 3232, 3250</productItems>
  </product>
</products>
